#
# Created by gmakemake (Ubuntu Sep  7 2011) on Sun Apr 21 13:04:38 2013
#

#
# Definitions
#

.SUFFIXES:
.SUFFIXES:	.a .o .c .C .cpp .s .S
.c.o:
		$(COMPILE.c) $<
.C.o:
		$(COMPILE.cc) $<
.cpp.o:
		$(COMPILE.cc) $<
.S.s:
		$(CPP) -o $*.s $<
.s.o:
		$(COMPILE.cc) $<
.c.a:
		$(COMPILE.c) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%
.C.a:
		$(COMPILE.cc) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%
.cpp.a:
		$(COMPILE.cc) -o $% $<
		$(AR) $(ARFLAGS) $@ $%
		$(RM) $%

CC =		gcc
CXX =		g++

RM = rm -f
AR = ar
LINK.c = $(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS)
LINK.cc = $(CXX) $(CXXFLAGS) $(CPPFLAGS) $(LDFLAGS)
COMPILE.c = $(CC) $(CFLAGS) $(CPPFLAGS) -c
COMPILE.cc = $(CXX) $(CXXFLAGS) $(CPPFLAGS) -c
CPP = $(CPP) $(CPPFLAGS)
########## Default flags (redefine these with a header.mak file if desired)
CXXFLAGS =	-ggdb
CFLAGS =	-ggdb
CLIBFLAGS =	-lm
CCLIBFLAGS =	
########## End of default flags


CPP_FILES =	tcp-clent1.C tcp-client.C tcp-client1.C
C_FILES =	
PS_FILES =	
S_FILES =	
H_FILES =	
SOURCEFILES =	$(H_FILES) $(CPP_FILES) $(C_FILES) $(S_FILES)
.PRECIOUS:	$(SOURCEFILES)
OBJFILES =	tcp-clent1.o 

#
# Main targets
#

all:	tcp-client tcp-client1 

tcp-client:	tcp-client.o $(OBJFILES)
	$(CXX) $(CXXFLAGS) -o tcp-client tcp-client.o $(OBJFILES) $(CCLIBFLAGS)

tcp-client1:	tcp-client1.o $(OBJFILES)
	$(CXX) $(CXXFLAGS) -o tcp-client1 tcp-client1.o $(OBJFILES) $(CCLIBFLAGS)

#
# Dependencies
#

tcp-clent1.o:	
tcp-client.o:	
tcp-client1.o:	

#
# Housekeeping
#

Archive:	archive.tgz

archive.tgz:	$(SOURCEFILES) Makefile
	tar cf - $(SOURCEFILES) Makefile | gzip > archive.tgz

clean:
	-/bin/rm $(OBJFILES) tcp-client.o tcp-client1.o core 2> /dev/null

realclean:        clean
	-/bin/rm -rf tcp-client tcp-client1 
